Plugin:
  current-version: '1.6.5'
  language: english
  off-permisions: false
  disable-all-banks: false
BankLoan:
  enable-bank: true
  maxloanuser: 1000
  timetax: 60
  taxesporcent: 10
BankEsmerald:
  enable-bank: true
  esmerald-price: 10
BankMoney:
  enable-bank: true
  max-money-save: 0
  interest-disbursted-system: true
  interest-porcent: 5
  disbursed-interest-per-time: 120
BankXP:
  enable-bank: true
  max-xp-levels-save: 0
BankTime:
  enable-bank: true
  give-money-per-period: 1
  time-per-period: 1
  max-money-give: -1
update:
  enable: true
send-metrics:
  enable: true
Lottery:
  max-global-tickets: -1
  buy-cost-per-ticket: 50
  get-winner-per-time: 120
